aave/aave-v3-core

package.json

The 'contributors' list was from V2 and needed an update.

Update package.json, contributors etc

---

package-lock.json
package.json

- Remove Open Zeppelin npm package due the repository contains the minimum needed Open Zeppelin smart contracts `.sol` files directly.
- Upgrade child dependencies

feat: clean dependencies and upgrade child dependencies

---

package-lock.json
package.json

Revert package.json and package-lock.json devDependencies to the prior working state.

fix: Revert dependencies to last working state

---

contracts/interfaces/IPool.sol

fix: Natspec for `IPool::swapBorrowRateMode()`

---

contracts/interfaces/IPoolConfigurator.sol
contracts/protocol/libraries/helpers/Errors.sol
contracts/protocol/pool/PoolConfigurator.sol
helpers/types.ts
test-suites/configurator.spec.ts
test-suites/validation-logic.spec.ts

Closes #615 
- Only allow disable borrowing if stableRateBorrowingEnabled is false
- Only allow stableRateBorrowingEnabled true when borrowing is disable

Enforce restrictions on stableRateBorrowingEnabled flag

---

contracts/protocol/libraries/logic/SupplyLogic.sol

refactor: Simplify `executeFinalizeTransfer`

---

contracts/protocol/libraries/logic/PoolLogic.sol

fix: Rename reserves to reservesList

---

contracts/protocol/libraries/logic/FlashLoanLogic.sol
contracts/protocol/libraries/logic/ValidationLogic.sol

fix: Move reservesData param to the beginning of the param list

---

hardhat.config.ts

ci: Increase compiler runs to 10000

---

contracts/mocks/oracle/SequencerOracle.sol
contracts/protocol/configuration/PoolAddressesProvider.sol
contracts/protocol/configuration/PoolAddressesProviderRegistry.sol
package-lock.json
package.json
test-suites/pausable-pool.spec.ts
test-suites/price-oracle-sentinel.spec.ts

- Add owner constructor parameter to contracts that inherits Ownable to support CREATE2 factory deployment

Add owner constructor parameter to contracts that inherits Ownable to support CREATE2 factory deployment

---

contracts/interfaces/ISequencerOracle.sol
contracts/mocks/oracle/SequencerOracle.sol
contracts/protocol/configuration/PriceOracleSentinel.sol
test-suites/price-oracle-sentinel.spec.ts

Updated price oracle sentinel interface

---

contracts/mocks/helpers/MockPeripheryContract.sol
helpers/contracts-helpers.ts
test-suites/aave-protocol-data-provider.spec.ts
test-suites/pool-addresses-provider.spec.ts
test-suites/pool-edge.spec.ts
test-suites/pool-l2.spec.ts

Add test cases for registering an existing proxy contract into PoolAddressesProvider

---

contracts/interfaces/IACLManager.sol

fix comments in IACLManager

---

contracts/protocol/tokenization/AToken.sol

Make AToken.transferOnLiquidation() virtual

---

contracts/protocol/libraries/logic/ReserveLogic.sol
test-suites/pool-edge.spec.ts

To close https://github.com/aave/aave-v3-core/issues/718

Fix for #718

---

contracts/protocol/libraries/logic/LiquidationLogic.sol
test-suites/liquidation-edge.spec.ts

Closes #746 
Huge shout out to @GopherJ for his contribution on #740 !

Fix condition of unsetting asset as collateral if its fully liquidated (with non-zero liquidationProtocolFee)

---

contracts/interfaces/IScaledBalanceToken.sol

docs: Fix docs of Mint and Burn events

---

contracts/interfaces/IAaveIncentivesController.sol
contracts/mocks/helpers/MockIncentivesController.sol
contracts/mocks/upgradeability/MockAToken.sol
contracts/protocol/libraries/logic/ConfiguratorLogic.sol
package-lock.json
package.json

Fix the handleAction of the IncentivesController interface

---

contracts/protocol/tokenization/base/EIP712Base.sol
contracts/protocol/tokenization/base/MintableIncentivizedERC20.sol
contracts/protocol/tokenization/base/ScaledBalanceTokenBase.sol

fix: Add BUSL to tokenization contracts

---

.github/workflows/node.js.yml
.github/workflows/release.yml

chore: Update Github Workflow to publish at NPM registry

---

.giatattributes
.gitattributes

not sure if it has any effects tbh

fix: typo fix

---

contracts/flashloan/base/FlashLoanReceiverBase.sol
contracts/flashloan/base/FlashLoanSimpleReceiverBase.sol

fix: Soften solidity version of FlashLoanBase contracts
