aave/aave-v3-core

- contracts/protocol/libraries/configuration/ReserveConfiguration.sol
**Identified by**:
Aave
**Scope**:
Replace `storage` with `memory` in `ReserveConfiguration::getLiquidationBonus()`
> fix: Use memory instead of storage in `getLiquidationBonus`

- package-lock.json
- package.json
- setup-test-env.sh
- Bump deploy-v3 dependency to latest version|
- Bump periphery-v3 dependency to latest version
- Explicitly disable rewards setup for tests
> misc: Bump deploy-v3 library to latest version

- README.md
The @aave/aave-v3-core package doesn't exist, replace with the actual package name which is @aave/core-v3
> fix: replace with correct npm package name

- contracts/protocol/tokenization/base/ScaledBalanceTokenBase.sol
Adding a comment for the target param in the `_burnScaled` function
> fix: add comment for undocumentted parameter

- contracts/interfaces/IPool.sol
- contracts/protocol/libraries/logic/BridgeLogic.sol
- contracts/protocol/pool/Pool.sol
This PR introduces the change of returning the actual backing amount when calling `backUnbacked`, which can
be smaller than the `amount` passed as an argument.
Closes #675
> fix: Return real backing amount when backUnbacked

- contracts/flashloan/interfaces/IFlashLoanReceiver.sol
- contracts/flashloan/interfaces/IFlashLoanSimpleReceiver.sol
- contracts/interfaces/IACLManager.sol
- contracts/interfaces/IAToken.sol
- contracts/interfaces/IAaveIncentivesController.sol
- contracts/interfaces/IAaveOracle.sol
- contracts/interfaces/ICreditDelegationToken.sol
- contracts/interfaces/IDelegationToken.sol
- contracts/interfaces/IERC20WithPermit.sol
- contracts/interfaces/IInitializableAToken.sol
- contracts/interfaces/IInitializableDebtToken.sol
- contracts/interfaces/IL2Pool.sol
- contracts/interfaces/IPool.sol
- contracts/interfaces/IPoolAddressesProvider.sol
- contracts/interfaces/IPoolAddressesProviderRegistry.sol
- contracts/interfaces/IPoolConfigurator.sol
- contracts/interfaces/IPoolDataProvider.sol
- contracts/interfaces/IPriceOracle.sol
- contracts/interfaces/IPriceOracleGetter.sol
- contracts/interfaces/IPriceOracleSentinel.sol
- contracts/interfaces/IReserveInterestRateStrategy.sol
- contracts/interfaces/IScaledBalanceToken.sol
- contracts/interfaces/ISequencerOracle.sol
- contracts/interfaces/IStableDebtToken.sol
- contracts/interfaces/IVariableDebtToken.sol
- contracts/misc/interfaces/IWETH.sol
Downgrade interface versions from `0.8.10` to `^0.8.0` to allow use within `0.8.x` minor versions
Fixes #697
> Fix modify interface versions to support all minor 0.8.x vers

- contracts/protocol/tokenization/AToken.sol
This PR makes AToken's `mintToTreasury` function overridable.
Having this function be virtual will make `AToken` easier to extend, e.g. for [grant-funded projects](https://twitter.com/AaveGrants/status/1586858440080572417) like [the one I'm working on](https://hackmd.io/@scopelift/Syg2nuNMo). It would also be consistent with the treatment of similar functions like AToken's `mint`, which is virtual:
https://github.com/aave/aave-v3-core/blob/f3e037b3638e3b7c98f0c09c56c5efde54f7c5d2/contracts/protocol/tokenization/AToken.sol#L87-L92
> Make mintToTreasury virtual so it can be overridden

- contracts/protocol/libraries/logic/ReserveLogic.sol
> Improving skip of updateState() by time, and caching dynamics for indexes

- contracts/protocol/libraries/helpers/Errors.sol
- contracts/protocol/libraries/logic/BridgeLogic.sol
- contracts/protocol/libraries/logic/FlashLoanLogic.sol
- contracts/protocol/libraries/logic/SupplyLogic.sol
- contracts/protocol/libraries/logic/ValidationLogic.sol
- contracts/protocol/pool/PoolConfigurator.sol
- helpers/types.ts
- test-suites/helpers/utils/calculations.ts
- test-suites/liquidity-indexes.spec.ts
- test-suites/pool-drop-reserve.spec.ts
- test-suites/pool-edge.spec.ts
https://github.com/aave/aave-v3-core/issues/730
The changes included in this PR are the following:
> Fixes #730. accruedToTreasury not being properly considered together with aToken supply

- Certora/certora/specs/pool.spec
- contracts/interfaces/IAToken.sol
- contracts/mocks/tokens/MockATokenRepayment.sol
- contracts/protocol/libraries/logic/BorrowLogic.sol
- contracts/protocol/libraries/logic/FlashLoanLogic.sol
- contracts/protocol/libraries/logic/LiquidationLogic.sol
- contracts/protocol/tokenization/AToken.sol
- hardhat.config.ts
- package-lock.json
- package.json
- test-suites/atoken-event-accounting.spec.ts
- test-suites/atoken-repay.spec.ts
- test-suites/helpers/utils/tokenization-events.ts
- test-suites/liquidation-atoken.spec.ts
- test-suites/pool-flashloan.spec.ts
- test-suites/variable-debt-token-events.spec.ts
- tsconfig.json
> Add onBehalfOf parameter to AToken handleRepayment function

- contracts/protocol/tokenization/base/ScaledBalanceTokenBase.sol
- test-suites/helpers/utils/tokenization-events.ts
> Do not emit `Transfer` and `Mint` events if senderBalanceIncrease is zero on aTokens transfer

- contracts/protocol/tokenization/base/ScaledBalanceTokenBase.sol
- test-suites/atoken-events.spec.ts
- test-suites/helpers/utils/tokenization-events.ts
> Optimizes logic of self transfers of aTokens

- contracts/protocol/libraries/configuration/ReserveConfiguration.sol
- contracts/protocol/libraries/configuration/UserConfiguration.sol
- contracts/protocol/libraries/helpers/Errors.sol
- contracts/protocol/libraries/helpers/Helpers.sol
- contracts/protocol/libraries/math/MathUtils.sol
- contracts/protocol/libraries/math/PercentageMath.sol
- contracts/protocol/libraries/math/WadRayMath.sol
- contracts/protocol/libraries/types/ConfiguratorInputTypes.sol
- contracts/protocol/libraries/types/DataTypes.sol
> Soften solidity version of Datatypes libraries

- contracts/interfaces/IAToken.sol
- package-lock.json
- package.json
> Fixes IAToken.transferUnderlyingTo function params

- contracts/protocol/libraries/logic/ReserveLogic.sol
- test-suites/__setup.spec.ts
- test-suites/helpers/scenario-engine.ts
- test-suites/pool-edge.spec.ts
> Fix calculation of IRs with non-zero unbacked and zero unbackedMintCap

- contracts/protocol/tokenization/AToken.sol
This is a follow up to https://github.com/aave/aave-v3-core/pull/726
It does two things:
* makes [`aToken.intialize`](https://github.com/aave/aave-v3-core/blob/f3e037b3638e3b7c98f0c09c56c5efde54f7c5d2/contracts/protocol/tokenization/AToken.sol#L53-L62) public and virtual
* makes [`aToken._transfer`](https://github.com/aave/aave-v3-core/blob/f3e037b3638e3b7c98f0c09c56c5efde54f7c5d2/contracts/protocol/tokenization/AToken.sol#L206-L211) virtual
Doing so will make `AToken` easier to extend, e.g. for [grant-funded projects](https://twitter.com/AaveGrants/status/1586858440080572417) like [the one I'm working on](https://hackmd.io/@scopelift/Syg2nuNMo).
I'd like `initialize()` to be public as well so that the override can just call `super.initialize(...)` to inherit all the current functionality …
> Make AToken's initialize and _transfer functions virtual so they can be extended

- contracts/interfaces/IPool.sol
Link to opened issue ---> [789](https://github.com/aave/aave-v3-core/issues/789)
I think the developer docs has been moved to [https://docs.aave.com/developers/](https://docs.aave.com/developers/)
> Fixed broken link in documentation

- contracts/dependencies/openzeppelin/contracts/IERC20.sol
It is problematic to have strict versioning in internal dependencies of contracts, especially those thought to be used/deployed partially in isolation (e.g. `DefaultReserveInterestRateStrategy`).
This just updates IERC20 from dependencies, as it is blocking for Aave v3 Ethereum
> Soften IERC20 versioning

- helper-hardhat-config.ts
- helpers/contracts-helpers.ts
- helpers/index.ts
- lib.tsconfig.json
- package-lock.json
- package.json
- Build typescript project at CI to export `helpers/index.ts` that exports types, contract helpers and constants of `@aave/core-v3` npm package
> fix: expose error list and types at npm package

- test-suites/aave-oracle.spec.ts
- test-suites/aave-protocol-data-provider.spec.ts
- test-suites/addresses-provider-registry.spec.ts
- test-suites/atoken-delegation-aware.spec.ts
- test-suites/atoken-edge.spec.ts
- test-suites/atoken-transfer.spec.ts
- test-suites/configurator-borrow-cap.spec.ts
- test-suites/configurator-liquidation-protocol-fee.spec.ts
- test-suites/configurator-supply-cap.spec.ts
- test-suites/configurator.spec.ts
- test-suites/pausable-pool.spec.ts
- test-suites/pool-addresses-provider.spec.ts
- test-suites/pool-authorized-flashloan.spec.ts
- test-suites/pool-edge.spec.ts
- test-suites/pool-flashloan.spec.ts
- test-suites/pool-l2.spec.ts
- test-suites/price-oracle-sentinel.spec.ts
- `await expect(sth).to.emit(sth).withArgs(lol)` will evaluate and throw
- `expect(await sth).to.emit(sth).withArgs(lol)` will always pass
Therefore this pr refactors the test-suite to always use the first.
> fix: await emit

- test-suites/aave-oracle.spec.ts
- test-suites/aave-protocol-data-provider.spec.ts
- test-suites/addresses-provider-registry.spec.ts
- test-suites/atoken-delegation-aware.spec.ts
- test-suites/atoken-edge.spec.ts
- test-suites/atoken-transfer.spec.ts
- test-suites/configurator-borrow-cap.spec.ts
- test-suites/configurator-liquidation-protocol-fee.spec.ts
- test-suites/configurator-supply-cap.spec.ts
- test-suites/configurator.spec.ts
- test-suites/helpers/scenarios/borrow-repayWithPermit-variable.json
- test-suites/pausable-pool.spec.ts
- test-suites/pool-addresses-provider.spec.ts
- test-suites/pool-authorized-flashloan.spec.ts
- test-suites/pool-drop-reserve.spec.ts
- test-suites/pool-edge.spec.ts
- test-suites/pool-flashloan.spec.ts
- test-suites/pool-get-reserve-address-by-id.spec.ts
- test-suites/pool-l2.spec.ts
- test-suites/price-oracle-sentinel.spec.ts
- test-suites/stable-debt-token.spec.ts
- test-suites/validation-logic.spec.ts
- test-suites/variable-debt-token.spec.ts
> Fix event checks in test cases

- contracts/protocol/libraries/logic/FlashLoanLogic.sol
- test-suites/pool-flashloan.spec.ts
- fix: don't require flashloan premium when premium is zero
- currently there are two cases in which flashloan premium is zero (being flashborrower & using mode != 0) - in the case of mode != 0, currently the receiver would receive `flashLoanPremium != 0` which will not be required to return. With the applied fix the premium will be correctly passed as `0`
> fix: dont commuicate wrong flash premium

- contracts/interfaces/IL2Pool.sol
- contracts/protocol/pool/L2Pool.sol
> fix: Return final withdraw amount in L2Pool withdraw fn

- contracts/dependencies/openzeppelin/contracts/Address.sol
- contracts/dependencies/openzeppelin/contracts/SafeERC20.sol
- Adds in `SafeERC20` as a dependency
- Upgrades `Address` library to a version that is compatible with `SafeERC20`
Closes #858
> feat: add SafeERC20 dependency

- contracts/protocol/pool/Pool.sol
It doesn't really make sense to initialize here with 9 and 0, and then in deploy script update it via common config to 5 and 4.
Generally it doesn't make to much sense to initialize potentially changing values in initialize as potentially every upgrade will reset them. Probably better to initialize as 0 and set them as part of the deploy pipeline (in fact that's already done for these two values).
> fix: remove default initialize
